name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b868a7549412fbb3cde01f1b708f7085868edf850399da18eaf04f704b4f6f1f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
