name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0928e18a1aba91862b8aaf7dbf3146bc61032a7c4139ec6446fb48c1bd0213e"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
