name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43d196bf5712ce9a2158231500b1beaeda8c0f119ccbf74f141415a4ec6678e5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
