name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d0dc1e7bca4234e796e4bdc4d0714e49e76109d4d1a8a5d757238e2ca1365f3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
