name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db75d029353fc147f014d3a8ec7229638f032964ad8be8a43f82aad49f964918"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
