name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27b2dd7ff49b752aeaf9b39b364c9f72c96368e2ae39a69843756242fe120798"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
