name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c13144fab63d577d158e802569c38fa400e9331d210c5947784105aa7c3de1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
