name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c787d8b458bbde0568aa648fda2a339b0ea2366ef6a59e0e5e2b614cbc43cf5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
