name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46a49572ff43cb10d81d30b0c9c303e41e6dde5aa9dbac2e11c367c566bd72dd"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
