name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5849bf049ac02dd4223140fdee31a2bb9b27f208698effa0937a62d10b8a3a6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
