name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7143a98887df8b4275191d4146fa1a8a9a52773b2caab884a336ed97dfc480be"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
