name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8c8b828af6bd70ac953d99d8d05a1e9fc4f14111d3409dd600621fd6097530"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
