name = "Layer"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "477756d31ef2e524c297b78ad25bac82c269338b5ada694587c476cf502ed1b4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
