name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0212fc3b4637d6b9968612996d47d884b773cfb83d26791f17b48ef652c3ade4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
