name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d20a0390c468b002bfa63eb72da733a23162deb1b2966aefa8a0cc8d3c878978"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
