name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b597898bccc1c19d12b10ece6c668355cae0f866311756ffc8bd43bd33ea6d90"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
