name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7619342bfb58f034c9fb38fa5031593202998d20d4e608fb8f0ce70a551572eb"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
