name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6c5b21036a4ee19bed1c22e7fd85c6625c53e327a399cd78f9fe9633209108c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
