name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d1e9440cb8ba8d9467921e5665a7d7b2fd6238b941e6fe716295302c699f32a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
