name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7193f9d14b1b03365dac7861d20f00ef1cb768c55fbedf295b3ca4f212471318"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
