name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f3752bd7ef58719b1e27b16823c35c810f8b205bb3f3a1b7edd1f1bad25b5fa"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
