name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7aab6c9bb3cc71b9dfecad1785221947e57a630238b73491126b88ea72181b6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
