name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cda42b933e7047bc8c3e6c3ac322bfd036071e4e2919a8947119268209cc38a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
