name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67272d2f916c752c8f508f6e85c914fcc94a1305812f737312ae7708c8f4f47d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
