name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67ce92df2ec73d7e752002890320001a4094efbdf28243dcc7f6ec707a78e246"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
