name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f983f1f28222272ce6906e0f6fe40f4e0c9e14aac148afe7571922540641515"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
