name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54dd8a9b63eb76797911380c3aef256203d5a8efe6832a4d2a850a22bcd1ac7f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
