name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c295373c28f25107d9352bd80c2dce4f66487896086d4f79a46b306e188de74"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
