name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "666fcc350a658ac903e33aca6a319a246e40e9086438db5d772d8b72dfcee7f0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
