name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d479aa986ded93d2cfe43c96f9c65d1a2e998b442563e8a0fa7e2d7327fe19ad"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
