name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bef23572d95d259649a9613d78f1d6e05c8fbbd6ca588a2ff58e4428821e767f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
