name = "Machines & Magecraft"
author = "Sebsa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e48a67b96be5d0ee79299c22f394f8535fdaa8d97448e79cbbebecc63962c13d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
